// Code generated by command: go run main.go -out guac_asm.s -stubs guac_stubs.go. DO NOT EDIT.

package resample

func ResampleF32x64_8x8(Out []float32, In []float32, Coefs []float32, PhaseIdx int, Phases int, SubsampleIdx uint64, SubsampleDelta uint64, Taps int) (PhaseIdxOut int, SubsampleIdxOut uint64)

func ResampleF32x64_16x16(Out []float32, In []float32, Coefs []float32, PhaseIdx int, Phases int, SubsampleIdx uint64, SubsampleDelta uint64, Taps int) (PhaseIdxOut int, SubsampleIdxOut uint64)

func SincF32s_8x1(Out []float32, Xmin float32, Xmax float32)
